### ISSUE TITLE
nlog.config case sensitivity

### ISSUE THREAD

**Issue by abuisine** [fremag/Nats-Tools#1]
running `dotnet publish` on a case sensitive file system (on Linux for instance) will fail as nlog.config is referenced in the .csproj whereas there is a NLog.config file in the repo

**Comment by fremag** [comment]
Hi,

Sorry for this very late answer, I have not worked on this small project for a long time...

I've fixed the file name so the publish command should work now.
I've tested with WSL on my computer running Windows and created some Github Actions to check and release some binairies for Windows and Linux.

I've added some new features too: request, reply, stat
